# Generated by Django 6.0.5 on 2026-05-26 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('current_stock', models.IntegerField()),
                ('unit_price_tzs', models.FloatField()),
            ],
            options={
                'db_table': 'forecasting_product',
            },
        ),
        migrations.CreateModel(
            name='SalesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_sold', models.IntegerField()),
                ('traffic_heavy', models.IntegerField()),
                ('weather_delay', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.product')),
            ],
            options={
                'db_table': 'forecasting_saleshistory',
            },
        ),
    ]
